import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import sharp from "sharp";

const approvedHeadline =
  "AI Engineer | Machine Learning & Deep Learning | Computer Vision | Automation | Python";
const approvedIntroduction =
  "I build AI systems that move from data and evaluation to useful, human-facing software.";
const evidenceSizes =
  "(min-width: 1200px) 46vw, (min-width: 768px) 80vw, 100vw";
const verifiedProjects = [
  {
    title: "GenoScene",
    category: "Featured AI",
    index: "01",
    alt:
      "GenoScene Learn interface showing DNA phenotyping guides and media tabs",
    repository: "https://github.com/mahmoudahmed2004/GenoScene_app",
  },
  {
    title: "OralVision",
    category: "Featured AI",
    index: "02",
    alt: "OralVision FastAPI classification interface",
    repository:
      "https://github.com/mahmoudahmed2004/oral-diseases-image-classification",
  },
  {
    title: "Corrective RAG System",
    category: "Featured AI",
    index: "03",
    alt: "Corrective RAG Streamlit document workspace",
    repository:
      "https://github.com/mahmoudahmed2004/Corrective-RAG-System",
  },
  {
    title: "Realistic Face DCGAN",
    category: "Featured AI",
    index: "04",
    alt: "Grid of synthetic 64 by 64 face samples generated by the DCGAN",
    repository:
      "https://github.com/mahmoudahmed2004/Realistic-Face-DCGAN",
  },
  {
    title: "Point of Sale System",
    category: "Software System",
    index: "05",
    alt: "Point of Sale desktop dashboard",
    repository: "https://github.com/mahmoudahmed2004/pos-system",
  },
  {
    title: "GenoScene Web Prototype",
    category: "Software System",
    index: "06",
    alt: "GenoScene bilingual web prototype interface",
    repository:
      "https://github.com/mahmoudahmed2004/GenoScene-website",
  },
] as const;

const metadataDescription =
  "AI Engineer building machine learning, deep learning, computer vision, retrieval, automation, and Python systems.";
const socialImagePath =
  "/images/og/neural-observatory-1200x630.png";

test("ships exact AI metadata and safely serialized project structured data", async ({
  page,
}) => {
  await page.goto("/");
  const origin = new URL(page.url()).origin;

  await expect(page).toHaveTitle("Mahmoud Ahmed Farouk — AI Engineer");
  await expect(page.locator('meta[name="description"]')).toHaveAttribute(
    "content",
    metadataDescription,
  );
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
    "href",
    origin,
  );
  await expect(page.locator('meta[property="og:type"]')).toHaveAttribute(
    "content",
    "website",
  );
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute(
    "content",
    `${origin}${socialImagePath}`,
  );
  await expect(page.locator('meta[property="og:image:width"]'))
    .toHaveAttribute("content", "1200");
  await expect(page.locator('meta[property="og:image:height"]'))
    .toHaveAttribute("content", "630");
  await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
    "content",
    "summary_large_image",
  );
  await expect(page.locator('meta[name="twitter:image"]')).toHaveAttribute(
    "content",
    `${origin}${socialImagePath}`,
  );

  const scripts = page.locator('script[type="application/ld+json"]');
  await expect(scripts).toHaveCount(1);
  const serialized = await scripts.textContent();
  expect(serialized).not.toContain("</script>");
  const graph = JSON.parse(serialized ?? "{}")["@graph"] as Array<
    Record<string, unknown>
  >;
  expect(graph.filter((entry) => entry["@type"] === "Person")).toHaveLength(1);
  expect(
    graph.filter((entry) => entry["@type"] === "SoftwareSourceCode"),
  ).toHaveLength(verifiedProjects.length);
  for (const entry of graph) {
    expect(String(entry["@id"])).toMatch(
      new RegExp(`^${origin.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/`),
    );
  }
});

test("serves canonical sitemap and permissive robots routes", async ({
  request,
}) => {
  const home = await request.get("/");
  const origin = new URL(home.url()).origin;

  const sitemap = await request.get("/sitemap.xml");
  expect(sitemap.status()).toBe(200);
  expect(sitemap.headers()["content-type"]).toContain("application/xml");
  const sitemapBody = await sitemap.text();
  expect(sitemapBody).toContain(`<loc>${origin}/</loc>`);
  expect(sitemapBody).toContain(`<loc>${origin}/cv</loc>`);
  expect((sitemapBody.match(/<url>/g) ?? [])).toHaveLength(2);

  const robots = await request.get("/robots.txt");
  expect(robots.status()).toBe(200);
  expect(robots.headers()["content-type"]).toContain("text/plain");
  const robotsBody = await robots.text();
  expect(robotsBody).toContain("User-Agent: *");
  expect(robotsBody).toContain("Allow: /");
  expect(robotsBody).not.toContain("Disallow:");
  expect(robotsBody).toContain(`Sitemap: ${origin}/sitemap.xml`);
});

test("serves the final 1200 by 630 Open Graph image", async ({ request }) => {
  const response = await request.get(socialImagePath);

  expect(response.status()).toBe(200);
  expect(response.headers()["content-type"]).toContain("image/png");
  const metadata = await sharp(await response.body()).metadata();
  expect(metadata.format).toBe("png");
  expect(metadata.width).toBe(1200);
  expect(metadata.height).toBe(630);
});

test("presents the approved AI-first identity and public actions", async ({
  page,
}) => {
  await page.goto("/");
  const hero = page.locator("#intro");

  await expect(
    hero.getByRole("heading", {
      level: 1,
      name: "Mahmoud Ahmed Farouk",
    }),
  ).toBeVisible();
  await expect(hero.getByText("AI Engineer", { exact: true })).toBeVisible();
  await expect(hero.getByText(approvedHeadline, { exact: true })).toBeVisible();
  await expect(
    hero.getByText(approvedIntroduction, { exact: true }),
  ).toBeVisible();
  await expect(hero.getByRole("link", { name: /explore selected work/i }))
    .toHaveAttribute("href", "#work");
  await expect(hero.getByRole("link", { name: "GitHub" }))
    .toHaveAttribute("href", "https://github.com/mahmoudahmed2004");
  await expect(hero.getByRole("link", { name: "LinkedIn" }))
    .toHaveAttribute(
      "href",
      "https://www.linkedin.com/in/mahmoud-farouk-72737924a",
    );
  await expect(hero.getByRole("link", { name: "Email" }))
    .toHaveAttribute("href", "mailto:maf.bns@gmail.com");
  await expect(hero.getByRole("link", { name: /download cv/i }))
    .toHaveAttribute("href", "/docs/mahmoud-ahmed-farouk-cv.pdf");
  await expect(
    page.getByRole("contentinfo").getByRole("link", { name: "Download CV" }),
  ).toHaveAttribute("href", "/docs/mahmoud-ahmed-farouk-cv.pdf");
  await expect(page.locator("body")).not.toContainText("01026889007");
});

test("reserves a decorative neural-bloom slot without portrait imagery", async ({
  page,
}) => {
  await page.goto("/");
  const hero = page.locator("#intro");
  const bloomSlot = hero.locator('[data-scene-slot="neural-bloom"]');

  await expect(hero.getByRole("img")).toHaveCount(0);
  await expect(hero.locator("picture")).toHaveCount(0);
  await expect(bloomSlot).toHaveCount(1);
  await expect(bloomSlot).toHaveAttribute("aria-hidden", "true");
  await expect(
    bloomSlot.locator('img[src="/images/neural-bloom-fallback.svg"][alt=""]'),
  ).toHaveCount(1);
  await expect(hero).toContainText("Observe · Learn · Evaluate · Deliver");
});

test("renders grouped expertise as semantic content", async ({ page }) => {
  await page.goto("/");
  await expect(
    page.getByRole("heading", { name: /signal to intelligence/i }),
  ).toBeVisible();
  await expect(page.getByRole("heading", { name: "Machine learning" }))
    .toBeVisible();
  await expect(page.getByRole("heading", { name: "Product engineering" }))
    .toBeVisible();
});

test("groups constellation skills in labelled semantic lists", async ({
  page,
}) => {
  await page.goto("/");
  const constellation = page.locator(
    'section[aria-labelledby="capability-title"]',
  );
  const groups = constellation.locator("ul[aria-labelledby]");

  await expect(
    constellation.getByRole("heading", {
      name: "One system, connected disciplines",
    }),
  ).toBeVisible();
  await expect(groups).toHaveCount(4);
  await expect(
    constellation
      .getByRole("list", { name: "Machine learning" })
      .getByRole("listitem"),
  ).toHaveText(["scikit-learn", "XGBoost", "LightGBM", "Pandas", "NumPy"]);
  await expect(
    constellation
      .getByRole("list", { name: "Product engineering" })
      .getByRole("listitem"),
  ).toHaveText(["FastAPI", "Django REST", "Flutter", "PySide6", "SQL"]);

  const decorativeConnectors = constellation.locator(
    'div[aria-hidden="true"]',
  );
  await expect(decorativeConnectors).toHaveCount(1);
  await expect(decorativeConnectors.locator("span")).toHaveCount(4);
});

test("keeps the core narrative visible without JavaScript", async ({
  browser,
}) => {
  const context = await browser.newContext({ javaScriptEnabled: false });
  const page = await context.newPage();

  try {
    await page.goto("/");
    await expect(
      page.getByRole("heading", {
        level: 1,
        name: "Mahmoud Ahmed Farouk",
      }),
    ).toBeVisible();
    await expect(
      page.getByText(approvedIntroduction, { exact: true }),
    ).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Signal to intelligence" }),
    ).toBeVisible();
  } finally {
    await context.close();
  }
});

test("keeps revealed content static when reduced motion is requested", async ({
  page,
}) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await expect(page.locator("#intro")).toBeVisible();

  const revealContent = page.locator("[data-reveal-content]");
  expect(await revealContent.count()).toBeGreaterThan(0);
  const activeAnimations = await revealContent.evaluateAll((nodes) =>
    nodes.reduce(
      (count, node) => count + node.getAnimations().length,
      0,
    ),
  );
  expect(activeAnimations).toBe(0);
});

test("fits the hero and capability narrative at 320 pixels", async ({
  page,
}) => {
  await page.setViewportSize({ width: 320, height: 720 });
  await page.goto("/");

  const widths = await page.evaluate(() => ({
    viewport: document.documentElement.clientWidth,
    document: document.documentElement.scrollWidth,
    body: document.body.scrollWidth,
  }));

  expect(widths.document).toBeLessThanOrEqual(widths.viewport);
  expect(widths.body).toBeLessThanOrEqual(widths.viewport);
  await expect(
    page.locator("#intro").getByRole("link", {
      name: "Explore selected work",
    }),
  ).toBeVisible();
  await expect(
    page.locator('section[aria-labelledby="capability-title"]'),
  ).toBeVisible();
});

test("renders all six verified projects and responsible-use notes", async ({
  page,
}) => {
  await page.goto("/");
  for (const title of [
    "GenoScene",
    "OralVision",
    "Corrective RAG System",
    "Realistic Face DCGAN",
    "Point of Sale System",
    "GenoScene Web Prototype",
  ]) {
    await expect(
      page.getByRole("heading", { name: title, exact: true }),
    ).toBeVisible();
  }
  await expect(page.getByText(/not definitive identity claims/i)).toBeVisible();
  await expect(page.getByText(/not a clinical diagnosis service/i)).toBeVisible();
  await expect(page.getByText(/synthetic model artifact/i)).toBeVisible();
});

test("labels repository-reported metrics with context", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("98.41%")).toBeVisible();
  await expect(
    page.getByText("Repository-reported EfficientNet-B3 evaluation").first(),
  ).toBeVisible();
});

test("keeps the verified 4 plus 2 project sequence and evidence contract", async ({
  page,
}) => {
  await page.goto("/");
  const featured = page.locator(
    'section#work[aria-labelledby="work-title"]',
  );
  const software = page.locator(
    'section[aria-labelledby="software-systems-title"]',
  );
  const featuredArticles = featured.getByRole("article");
  const softwareArticles = software.getByRole("article");

  await expect(featuredArticles).toHaveCount(4);
  await expect(softwareArticles).toHaveCount(2);
  await expect(
    featuredArticles.getByRole("heading", { level: 3 }),
  ).toHaveText(verifiedProjects.slice(0, 4).map((project) => project.title));
  await expect(
    softwareArticles.getByRole("heading", { level: 3 }),
  ).toHaveText(verifiedProjects.slice(4).map((project) => project.title));

  for (const project of verifiedProjects) {
    const article = page.getByRole("article", {
      name: project.title,
      exact: true,
    });
    const position = article.locator('[aria-label="Project position"]');
    const image = article.getByRole("img", {
      name: project.alt,
      exact: true,
    });

    await expect(position.locator("span").first()).toHaveText(project.index);
    await expect(position.getByText(project.category, { exact: true }))
      .toBeVisible();
    await expect(image).toHaveAttribute("alt", project.alt);
    await expect(image).toHaveAttribute("width", "1600");
    await expect(image).toHaveAttribute("height", "1000");
    await expect(image).toHaveAttribute("sizes", evidenceSizes);
  }
});

test("associates metrics, team attribution, and responsible-use notes with the correct projects", async ({
  page,
}) => {
  await page.goto("/");
  const oralVision = page.getByRole("article", {
    name: "OralVision",
    exact: true,
  });
  const dcgan = page.getByRole("article", {
    name: "Realistic Face DCGAN",
    exact: true,
  });
  const genoScene = page.getByRole("article", {
    name: "GenoScene",
    exact: true,
  });

  await expect(oralVision.getByText("98.41%", { exact: true })).toBeVisible();
  await expect(oralVision.getByText("98.14%", { exact: true })).toBeVisible();
  await expect(
    oralVision.getByText(
      "Repository-reported EfficientNet-B3 evaluation",
      { exact: true },
    ),
  ).toHaveCount(2);
  await expect(dcgan.getByText("2.2427", { exact: true })).toBeVisible();
  await expect(dcgan.getByText("0.7276", { exact: true })).toBeVisible();
  await expect(
    dcgan.getByText("Repository-reported final training loss", {
      exact: true,
    }),
  ).toHaveCount(2);
  await expect(genoScene.getByText("98.41%", { exact: true })).toHaveCount(0);

  const teamAttribution =
    "Team graduation project. Contributions are described without claiming sole authorship.";
  await expect(
    genoScene.getByText(teamAttribution, { exact: true }),
  ).toBeVisible();
  await expect(page.getByText(teamAttribution, { exact: true })).toHaveCount(1);

  const responsibleUse = [
    {
      title: "GenoScene",
      text:
        "Research-oriented probabilities are not definitive identity claims. Any portrait is illustrative.",
    },
    {
      title: "OralVision",
      text:
        "This is a research classifier and is not a clinical diagnosis service.",
    },
    {
      title: "Realistic Face DCGAN",
      text:
        "Every face shown is a synthetic model artifact, not a real person supplied as project evidence.",
    },
    {
      title: "GenoScene Web Prototype",
      text:
        "The prototype explores probabilistic phenotype presentation and is not a definitive identification tool.",
    },
  ] as const;
  const notes = page.locator('aside[aria-label="Responsible use note"]');

  await expect(notes).toHaveCount(4);
  await expect(notes.getByText("Research context", { exact: true }))
    .toHaveCount(4);
  for (const note of responsibleUse) {
    const article = page.getByRole("article", {
      name: note.title,
      exact: true,
    });
    const aside = article.locator('aside[aria-label="Responsible use note"]');
    await expect(aside).toHaveCount(1);
    await expect(aside.getByText(note.text, { exact: true })).toBeVisible();
  }
});

test("keeps repository actions project-specific and preserves editorial reading order", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");

  for (const [projectIndex, project] of verifiedProjects.entries()) {
    const article = page.getByRole("article", {
      name: project.title,
      exact: true,
    });
    const repository = article.getByRole("link", {
      name: `View repository for ${project.title} (opens in a new tab)`,
      exact: true,
    });
    const runtimeContract = await article.evaluate((node) => {
      const children = Array.from(node.children);
      const heading = node.querySelector("h3");
      const image = node.querySelector("img");
      const link = node.querySelector('a[target="_blank"]');
      if (!heading || !image || !link) {
        return null;
      }
      return {
        contentOrder: [
          children.findIndex((child) => child.contains(heading)),
          children.findIndex((child) => child.contains(image)),
          children.findIndex((child) => child.contains(link)),
        ],
        headingLeft: Math.round(heading.getBoundingClientRect().left),
        imageLeft: Math.round(image.getBoundingClientRect().left),
      };
    });

    await expect(repository).toHaveAttribute("href", project.repository);
    await expect(repository).toHaveAttribute("target", "_blank");
    expect(runtimeContract?.contentOrder).toEqual([0, 1, 2]);
    if (projectIndex % 2 === 0) {
      expect(runtimeContract?.imageLeft).toBeGreaterThan(
        runtimeContract?.headingLeft ?? Number.POSITIVE_INFINITY,
      );
    } else {
      expect(runtimeContract?.imageLeft).toBeLessThan(
        runtimeContract?.headingLeft ?? Number.NEGATIVE_INFINITY,
      );
    }
  }
});

test("keeps project actions touch-sized and evidence static on narrow or reduced-motion views", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  const repositoryActions = page.getByRole("link", {
    name: /view repository for .*opens in a new tab/i,
  });

  await expect(repositoryActions).toHaveCount(6);
  const actionHeights = await repositoryActions.evaluateAll((links) =>
    links.map((link) => link.getBoundingClientRect().height),
  );
  expect(actionHeights.every((height) => height >= 44)).toBe(true);

  await page.setViewportSize({ width: 320, height: 720 });
  const widths = await page.evaluate(() => ({
    viewport: document.documentElement.clientWidth,
    document: document.documentElement.scrollWidth,
    body: document.body.scrollWidth,
  }));
  expect(widths.document).toBeLessThanOrEqual(widths.viewport);
  expect(widths.body).toBeLessThanOrEqual(widths.viewport);

  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.reload({ waitUntil: "domcontentloaded" });
  const firstProject = page.getByRole("article", {
    name: "GenoScene",
    exact: true,
  });
  const firstEvidence = firstProject.getByRole("img", {
    name: verifiedProjects[0].alt,
    exact: true,
  });
  await firstProject.hover();
  expect(
    await firstEvidence.evaluate((image) => getComputedStyle(image).transform),
  ).toBe("none");
});

test("presents graduate status, certificates, and safe contact methods", async ({
  page,
}) => {
  await page.goto("/");
  await expect(
    page.getByText(
      "Computer Science Graduate — Modern Academy, Class of 2026",
    ),
  ).toBeVisible();
  await expect(
    page.getByRole("heading", { name: "Certificates" }),
  ).toBeVisible();
  await expect(page.getByRole("link", { name: /linkedin/i }).last())
    .toHaveAttribute(
      "href",
      "https://www.linkedin.com/in/mahmoud-farouk-72737924a",
    );
  await expect(page.locator('a[href^="tel:"]')).toHaveCount(0);

  const timeline = page.locator(
    'section#experience[aria-labelledby="experience-title"]',
  );
  await expect(timeline.getByRole("list")).toHaveCount(1);
  await expect(timeline.getByRole("listitem")).toHaveCount(6);
  await expect(
    timeline.getByRole("heading", { level: 3 }),
  ).toHaveText([
    "Eram Group",
    "INSTANT Software Solutions",
    "Div Academy",
    "IT Gate Academy",
    "Enactus",
    "Modern Academy",
  ]);

  const contact = page.locator(
    'section#contact[aria-labelledby="contact-title"]',
  );
  await expect(contact.getByRole("link")).toHaveCount(3);
  await expect(contact.getByRole("link", { name: /email/i }))
    .toHaveAttribute("href", "mailto:maf.bns@gmail.com");
  await expect(contact.getByRole("link", { name: /github/i }))
    .toHaveAttribute("href", "https://github.com/mahmoudahmed2004");
  await expect(contact.getByRole("link", { name: /linkedin/i }))
    .toHaveAttribute(
      "href",
      "https://www.linkedin.com/in/mahmoud-farouk-72737924a",
    );
  await expect(contact.locator("form")).toHaveCount(0);
});

test("keeps the native certificate dialog dismissible and restores its trigger", async ({
  page,
}) => {
  await page.goto("/");
  const trigger = page.getByRole("button", {
    name: /open ai diploma certificate/i,
  });

  await trigger.focus();
  await trigger.click();
  const dialog = page.getByRole("dialog", { name: /ai diploma/i });
  await expect(dialog).toBeVisible();
  await expect(dialog.locator("img")).toHaveAttribute(
    "src",
    /instant-ai-diploma/,
  );
  await expect(dialog.getByText("INSTANT Software Solutions")).toBeVisible();
  await expect(dialog.getByText("2025", { exact: true })).toBeVisible();
  await expect(dialog.getByText(/170 training hours/i)).toBeVisible();
  await expect(dialog.getByRole("link", { name: /open original file/i }))
    .toHaveAttribute(
      "href",
      "/images/certificates/instant-ai-diploma.webp",
    );
  await expect(page.locator("body")).toHaveCSS("overflow", "hidden");

  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await expect(page.locator("body")).not.toHaveCSS("overflow", "hidden");

  await trigger.click();
  await page.getByRole("button", { name: /^close/i }).click();
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();

  await trigger.click();
  await page.getByRole("dialog", { name: /ai diploma/i }).evaluate((node) => {
    node.dispatchEvent(new MouseEvent("click", { bubbles: true }));
  });
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await expect(page.locator("body")).not.toHaveCSS("overflow", "hidden");
});

test("centers the certificate dialog with safe viewport insets", async ({
  page,
}) => {
  const viewports = [
    { width: 320, height: 720 },
    { width: 390, height: 844 },
    { width: 1440, height: 1000 },
  ] as const;

  for (const viewport of viewports) {
    await page.setViewportSize(viewport);
    await page.goto("/");
    const trigger = page.getByRole("button", {
      name: /open ai diploma certificate/i,
    });
    await trigger.click();
    const dialog = page.getByRole("dialog", { name: /ai diploma/i });
    await expect(dialog).toBeVisible();

    const geometry = await dialog.evaluate((node) => {
      const rect = node.getBoundingClientRect();
      return {
        left: rect.left,
        right: window.innerWidth - rect.right,
        top: rect.top,
        bottom: window.innerHeight - rect.bottom,
        width: rect.width,
        height: rect.height,
      };
    });

    const geometryContext = JSON.stringify({ viewport, geometry });
    expect(geometry.left, geometryContext).toBeGreaterThanOrEqual(8);
    expect(geometry.right, geometryContext).toBeGreaterThanOrEqual(8);
    expect(geometry.top, geometryContext).toBeGreaterThanOrEqual(8);
    expect(geometry.bottom, geometryContext).toBeGreaterThanOrEqual(8);
    expect(Math.abs(geometry.left - geometry.right)).toBeLessThanOrEqual(1);
    expect(Math.abs(geometry.top - geometry.bottom)).toBeLessThanOrEqual(1);
    expect(geometry.width).toBeLessThanOrEqual(viewport.width - 16);
    expect(geometry.height).toBeLessThanOrEqual(viewport.height - 16);

    await page.keyboard.press("Escape");
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toBeFocused();
    await expect(page.locator("body")).not.toHaveCSS("overflow", "hidden");
  }
});

test("provides an accessible keyboard skip target on the printable CV", async ({
  page,
}) => {
  await page.goto("/cv");
  const skipLink = page.getByRole("link", { name: "Skip to content" });
  const main = page.locator("main#main-content");

  await expect(skipLink).toHaveAttribute("href", "#main-content");
  await expect(main).toHaveCount(1);
  await page.keyboard.press("Tab");
  await expect(skipLink).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(/\/cv#main-content$/);

  const accessibility = await new AxeBuilder({ page }).analyze();
  expect(accessibility.violations).toEqual([]);
});

test("renders a printable server CV from the shared public portfolio", async ({
  page,
}) => {
  await page.goto("/cv");
  await expect(
    page.getByRole("heading", { level: 1, name: "Mahmoud Ahmed Farouk" }),
  ).toBeVisible();
  for (const heading of [
    "Profile",
    "Skills",
    "Selected projects",
    "Experience",
    "Education",
    "Certificates",
  ]) {
    await expect(page.getByRole("heading", { name: heading })).toBeVisible();
  }
  await expect(
    page.getByRole("heading", {
      level: 3,
      name: "GenoScene",
      exact: true,
    }),
  ).toBeVisible();
  await expect(page.getByText("Eram Group", { exact: true })).toBeVisible();
  await expect(page.locator('a[href^="tel:"]')).toHaveCount(0);
  await expect(page.locator("body")).not.toContainText("01026889007");

  await page.emulateMedia({ media: "print" });
  await expect(page.locator("body")).toHaveCSS(
    "background-color",
    "rgb(255, 255, 255)",
  );
  await expect(page.locator("body")).toHaveCSS("color", "rgb(0, 0, 0)");

  const printColors = await page.evaluate(() => {
    const selectors = [
      ".cv-page",
      ".cv-kicker",
      ".cv-section > h2",
      ".cv-compact",
      ".cv-entry-heading > p",
      ".cv-certificate span",
      ".cv-footer",
    ];

    return selectors.map((selector) => {
      const node = document.querySelector(selector);
      if (!node) {
        throw new Error(`Missing print-color fixture: ${selector}`);
      }

      return {
        selector,
        color: getComputedStyle(node).color,
        background: getComputedStyle(node).backgroundColor,
      };
    });
  });

  for (const style of printColors) {
    expect(style.color, style.selector).toBe("rgb(0, 0, 0)");
  }
  expect(printColors[0]?.background).toBe("rgb(255, 255, 255)");

  const repository = page.getByRole("link", { name: "Repository" }).first();
  const repositoryPrint = await repository.evaluate((node) => ({
    color: getComputedStyle(node).color,
    pseudoColor: getComputedStyle(node, "::after").color,
    pseudoContent: getComputedStyle(node, "::after").content,
  }));
  expect(repositoryPrint.color).toBe("rgb(0, 0, 0)");
  expect(repositoryPrint.pseudoColor).toBe("rgb(0, 0, 0)");
  expect(repositoryPrint.pseudoContent).toContain("github.com");
});

test("keeps the Neural Bloom fallback when reduced motion is requested", async ({
  page,
}) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");

  const bloom = page.locator('[data-scene-quality="static"]');
  await expect(bloom).toBeVisible();
  await expect(
    bloom.locator('img[src="/images/neural-bloom-fallback.svg"]'),
  ).toBeVisible();
  await expect(page.locator("canvas")).toHaveCount(0);
  await expect(page.locator("[data-observatory-phase]")).toHaveCount(5);
});

test("keeps one ready Neural Bloom canvas across capable quality tiers", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/");

  const bloom = page.locator(".neural-bloom-loader");
  const sceneLayer = bloom.locator(".neural-bloom-scene-layer");
  const canvas = bloom.locator("canvas");
  const fallback = bloom.locator(".neural-bloom-fallback");

  await expect(bloom).toHaveAttribute("data-scene-quality", "high");
  await expect(sceneLayer).toHaveAttribute("data-scene-ready", "true");
  await expect(sceneLayer).toHaveCSS("opacity", "1");
  await expect(canvas).toHaveCount(1);
  await expect(fallback).toBeVisible();
  await canvas.evaluate((node) => {
    node.setAttribute("data-runtime-canvas", "retained");
  });

  await page.setViewportSize({ width: 390, height: 844 });
  await expect(bloom).toHaveAttribute("data-scene-quality", "low");
  await expect(sceneLayer).toHaveAttribute("data-scene-ready", "true");
  await expect(sceneLayer).toHaveCSS("opacity", "1");
  await expect(
    bloom.locator('canvas[data-runtime-canvas="retained"]'),
  ).toHaveCount(1);

  await page.setViewportSize({ width: 1440, height: 1000 });
  await expect(bloom).toHaveAttribute("data-scene-quality", "high");
  await expect(sceneLayer).toHaveAttribute("data-scene-ready", "true");
  await expect(sceneLayer).toHaveCSS("opacity", "1");
  await expect(
    bloom.locator('canvas[data-runtime-canvas="retained"]'),
  ).toHaveCount(1);
  await expect(fallback).toBeVisible();
});
